### ISSUE TITLE
Write an entire separate api

### ISSUE THREAD

**Issue by veritem** [fally-app/frontend#96]
I think we might want to write a different backend API for this

**Comment by didiermun** [comment]
Do you mean a different app that acts as a server/ backend application? to provide APIs??

**Comment by didiermun** [comment]
> I think we might want to write a different backend API for this

ok that is good then and will sound fresh with codes more cleaner and displayable

**Comment by veritem** [comment]
I've changed my mind, I'm not going to use anything else for this app just code needs to be reviewed again and cleaned again
